# Count min-sketch

## Alejandro González

In [0]:
import numpy as np
import math

In [75]:
# Request data stream
S = [str(x) for x in input('Data Stream (elements separated by sace): ').split()] 

Data Stream (elements separated by sace): A B C A A D D


In [81]:
# Request error probability and error factor and calculate d and w
delta = float(input('Error probability (delta - typically: 0.1 - 0.001): '))
epsilon = float(input('Error factor (epsilon - typically: 0.5 - 0.01): '))

# Depth or number of hash functions
d = int(np.log(1/delta))

# Width
w = int(math.exp(1) / epsilon)
print(d, w0)

Error probability (delta - typically: 0.1 - 0.001): 0.001
Error factor (epsilon - typically: 0.1 - 0.001): 0.3
6 9


In [85]:
# Count number of unique items in the stream
N = len(np.unique(S))
elements = list(np.unique(S))
elements

['A', 'B', 'C', 'D']

In [83]:
# Create the hash matrix
hash_matrix = np.random.randint(w, size=(N, d))
hash_matrix

array([[1, 1, 3, 0, 6, 0],
       [6, 7, 0, 0, 6, 0],
       [8, 8, 1, 8, 2, 1],
       [1, 5, 2, 3, 3, 7]])

In [87]:
sketch = np.zeros((d, w))
sketch

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [88]:
for item in S:
  for h in range(d):
    sketch[h][hash_matrix[elements.index(item)][h]] += 1 
    
sketch

array([[0., 5., 0., 0., 0., 0., 1., 0., 1.],
       [0., 3., 0., 0., 0., 2., 0., 1., 1.],
       [1., 1., 2., 3., 0., 0., 0., 0., 0.],
       [4., 0., 0., 2., 0., 0., 0., 0., 1.],
       [0., 0., 1., 2., 0., 0., 4., 0., 0.],
       [4., 1., 0., 0., 0., 0., 0., 2., 0.]])

In [94]:
c = input('Frequency of: ')
l = []
for h in range(d):
  l.append(sketch[h][hash_matrix[elements.index(c)][h]])
  
count = str(int(min(l)))
print('The count of ' + c + ' in the stream is: ' + count)

Frequency of: D
The count of D in the stream is: 2
