# Count min-sketch

## Alejandro González

### Dependencies
* Numpy
* Math

In [0]:
import numpy as np
import math

### Implementation


#### Requests the user a data stream
Input: Data stream

In [9]:
# Request data stream
S = [str(x) for x in input('Data Stream (elements separated by space): ').split()] 

Data Stream (elements separated by space): A S D F G H G R D W S A S A S A S A S A S A S W Q Q A S D E E D W S D E D F E E E


Input: Delta and epsilon

These values are necessary to calculate the number of hash functions ***h*** and the depth ***w***.

In [10]:
# Request error probability and error factor and calculate d and w
delta = float(input('Error probability (delta - typically: 0.05 - 0.001): '))
epsilon = float(input('Error factor (epsilon - typically: 0.5 - 0.1): '))

# Depth or number of hash functions
d = int(np.log(1/delta))

# Width
w = int(math.exp(1) / epsilon)

Error probability (delta - typically: 0.1 - 0.001): 0.01
Error factor (epsilon - typically: 0.5 - 0.01): 0.2


In [11]:
# Count number of unique items in the stream
N = len(np.unique(S))
elements = list(np.unique(S))
elements

['A', 'D', 'E', 'F', 'G', 'H', 'Q', 'R', 'S', 'W']

### Hash matrix and sketch

In [12]:
# Create the hash matrix
hash_matrix = np.random.randint(w, size=(N, d))
hash_matrix

array([[ 0, 11,  8, 11],
       [ 3,  8,  3,  9],
       [ 1,  7, 10,  8],
       [ 0,  6,  7, 12],
       [11,  0,  7,  1],
       [ 7,  2, 10,  7],
       [ 0,  7,  7,  3],
       [12,  3, 12,  7],
       [ 3,  0,  4,  6],
       [11, 12, 12, 12]])

In [13]:
sketch = np.zeros((d, w))
sketch

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
for item in S:
  for h in range(d):
    sketch[h][hash_matrix[elements.index(item)][h]] += 1 
sketch

array([[12.,  6.,  0., 16.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  5.,  1.],
       [12.,  0.,  1.,  1.,  0.,  0.,  2.,  8.,  6.,  0.,  0.,  8.,  3.],
       [ 0.,  0.,  0.,  6., 10.,  0.,  0.,  6.,  8.,  0.,  7.,  0.,  4.],
       [ 0.,  2.,  0.,  2.,  0.,  0., 10.,  2.,  6.,  6.,  0.,  8.,  5.]])

### Count of element
Requests the desired element to be counted

In [15]:
c = input('Frequency of: ')
l = []
for h in range(d):
  l.append(sketch[h][hash_matrix[elements.index(c)][h]])
  
count = str(int(min(l)))
print('The count of ' + c + ' in the stream is: ' + count)

Frequency of: A
The count of A in the stream is: 8
